version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - gem install bundler
      - make install
  build:
    commands:
      - make test
  post_build:
    commands:
      - make gem-test
